Repository scalecube/scalecube-services, pull requests merged in 2018-06, with the labels that each got.

#113 service router predicates
  pom.xml
  services/pom.xml
  services/src/main/java/io/scalecube/services/registry/ServiceRegistryImpl.java
  services/src/main/java/io/scalecube/services/routing/RoundRobinServiceRouter.java
Labels: ready for review

#114 improvements for benchmarks
  benchmarks/src/main/java/io/scalecube/services/benchmarks/OneWayBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/OneWayCallBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/RequestBidirectionalEchoCallBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/RequestManyBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/RequestManyCallBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/RequestOneBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/RequestOneCallBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/ServicesBenchmarksSettings.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/ServicesBenchmarksState.java
Labels: ready for review

#124 Fixed using counter in round-robin strategy
  services/src/main/java/io/scalecube/services/routing/RoundRobinServiceRouter.java
Labels: ready for review

#125 Add annotation AfterConstruct
  services-api/src/main/java/io/scalecube/services/annotations/AfterConstruct.java
  services/src/main/java/io/scalecube/services/Reflect.java
Labels: ready for review

#123 Improve Microservices API
  benchmarks/src/main/java/io/scalecube/services/benchmarks/ServicesBenchmarksState.java
  services/src/main/java/io/scalecube/services/Microservices.java
  services/src/main/java/io/scalecube/services/Reflect.java
  services/src/main/java/io/scalecube/services/ServiceCall.java
  services/src/main/java/io/scalecube/services/transport/HeadAndTail.java
  services/src/main/java/io/scalecube/services/transport/LocalServiceMessageHandler.java
  services/src/test/java/io/scalecube/services/CoarseGrainedServiceImpl.java
  services/src/test/java/io/scalecube/services/ErrorFlowTest.java
  services/src/test/java/io/scalecube/services/LocalServiceTest.java
  services/src/test/java/io/scalecube/services/ReflectTest.java
  services/src/test/java/io/scalecube/services/RemoteServiceTest.java
  services/src/test/java/io/scalecube/services/RoutersTest.java
  services/src/test/java/io/scalecube/services/ServiceCallTest.java
  services/src/test/java/io/scalecube/services/a/b/testing/ServiceTagsExample.java
  services/src/test/java/io/scalecube/services/streaming/SimpleQuoteService.java
  services/src/test/java/io/scalecube/services/streaming/StreamingServiceTest.java
  services/src/test/java/io/scalecube/services/transport/HeadAndTailTest.java
Labels: ready for review

#136 Add supperss warnings unchecked
  services/src/main/java/io/scalecube/services/ServiceCall.java
Labels: enhancement, ready for review

#137 Fixed round robin tests
  services/src/test/java/io/scalecube/services/RemoteServiceTest.java
Labels: ready for review

#130 Work on ServiceTransportTest
  benchmarks/pom.xml
  pom.xml
  rsocket-transport/pom.xml
  rsocket-transport/src/main/java/io/scalecube/services/transport/rsocket/client/RSocketClientTransport.java
  rsocket-transport/src/main/java/io/scalecube/services/transport/rsocket/client/RSocketServiceClientAdapter.java
  rsocket-transport/src/main/java/io/scalecube/services/transport/rsocket/server/RSocketServerTransport.java
  rsocket-transport/src/test/java/MyPojo.java
  services-api/pom.xml
  services-codec-jackson/pom.xml
  services-codec/pom.xml
  services-transport/pom.xml
  services/pom.xml
  services/src/test/java/io/scalecube/services/ServiceTransportTest.java
  services/src/test/java/io/scalecube/services/streaming/QuoteService.java
  services/src/test/java/io/scalecube/services/streaming/SimpleQuoteService.java
  services/src/test/java/io/scalecube/services/streaming/StreamingServiceTest.java
Labels: ready for review

#135 Refactor code for routers
  services-api/src/main/java/io/scalecube/services/annotations/Inject.java
  services-api/src/main/java/io/scalecube/services/annotations/Null.java
  services-api/src/main/java/io/scalecube/services/annotations/NullRouter.java
  services-api/src/main/java/io/scalecube/services/routing/Router.java
  services/src/main/java/io/scalecube/services/Microservices.java
  services/src/main/java/io/scalecube/services/Reflect.java
  services/src/main/java/io/scalecube/services/ServiceCall.java
  services/src/main/java/io/scalecube/services/routing/RandomServiceRouter.java
  services/src/main/java/io/scalecube/services/routing/RoundRobinServiceRouter.java
  services/src/main/java/io/scalecube/services/routing/Routers.java
  services/src/test/java/io/scalecube/services/DummyRouter.java
  services/src/test/java/io/scalecube/services/RoutersTest.java
  services/src/test/java/io/scalecube/services/a/b/testing/CanaryTestingRouter.java
Labels: enhancement

#147 Add Id for microservices instance and publish in the cluster
  benchmarks/src/main/java/io/scalecube/services/benchmarks/RouterBenchmarks.java
  services/src/main/java/io/scalecube/services/Microservices.java
  services/src/main/java/io/scalecube/services/discovery/ServiceScanner.java
Labels: enhancement, ready for review

#143 Improved benchmarks
  benchmarks/pom.xml
  benchmarks/src/main/java/io/scalecube/services/benchmarks/BenchmarksSettings.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/BenchmarksState.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/OneWayBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/OneWayCallBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/RequestBidirectionalEchoCallBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/RequestManyBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/RequestManyCallBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/RequestManyLatencyBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/RequestOneBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/RequestOneCallBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/RouterBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/RouterBenchmarksState.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/ServicesBenchmarksSettings.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/ServicesBenchmarksState.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/jmh/HeadAndTailBenchmarks.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/jmh/RouterBenchmarks.java
  benchmarks/src/main/resources/log4j2.xml
  pom.xml
Labels: ready for review

#153 Added dependency on scalecube-benchmarks and refactoring
  benchmarks/pom.xml
  benchmarks/src/main/java/io/scalecube/services/benchmarks/BenchmarksSettings.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/BenchmarksState.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/OneWayBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/OneWayCallBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/RequestManyBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/RequestManyCallBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/RequestManyLatencyBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/RequestOneBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/RequestOneCallBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/RouterBenchmarksRunner.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/RouterBenchmarksState.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/ServicesBenchmarksState.java
  pom.xml
Labels: ready for review

#160 Fix decoder issue request-many
  benchmarks/pom.xml
  benchmarks/src/main/java/io/scalecube/services/benchmarks/services/BenchmarkService.java
  benchmarks/src/main/java/io/scalecube/services/benchmarks/services/BenchmarkServiceImpl.java
  pom.xml
  rsocket-transport/src/main/java/io/scalecube/services/transport/rsocket/client/RSocketClientTransport.java
  rsocket-transport/src/main/java/io/scalecube/services/transport/rsocket/server/RSocketServerTransport.java
  rsocket-transport/src/main/java/io/scalecube/services/transport/rsocket/server/RSocketServiceAcceptor.java
  services-codec/src/main/java/io/scalecube/services/codec/ServiceMessageCodec.java
Labels: ready for review
