Repository scalecube/scalecube-services, pull requests merged in 2019-03, with the labels that each got.

#510 use switchOnFirst replacing HeadAndTail
  pom.xml
  services-api/pom.xml
  services-api/src/main/java/io/scalecube/services/HeadAndTail.java
  services-api/src/test/java/io/scalecube/services/HeadAndTailTest.java
  services-gateway-http/src/main/java/io/scalecube/services/gateway/http/HttpGatewayAcceptor.java
  services-transport-rsocket/src/main/java/io/scalecube/services/transport/rsocket/RSocketServiceAcceptor.java
  services/pom.xml
  services/src/main/java/io/scalecube/services/ServiceCall.java
  services/src/test/java/io/scalecube/services/ServiceRemoteTest.java
Labels: Improvement ↗️, discussion 💬

#495 Added JMX support for microservices instance
  services-discovery/src/main/java/io/scalecube/services/discovery/ScalecubeServiceDiscovery.java
  services/src/main/java/io/scalecube/services/Microservices.java
  services/src/main/java/io/scalecube/services/MicroservicesMBean.java
Labels: Improvement ↗️, 👁️ ready for review 👁️

#526 refactor service call
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/transport/BenchmarkServiceState.java
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/transport/InfiniteStreamBenchmark.java
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/transport/RequestOneBenchmark.java
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/transport/RequestVoidBenchmark.java
  services-examples/src/main/java/io/scalecube/services/examples/BootstrapExample.java
  services-examples/src/main/java/io/scalecube/services/examples/exceptions/ExceptionMapperExample.java
  services-examples/src/main/java/io/scalecube/services/examples/gateway/HttpGatewayStub.java
  services-examples/src/main/java/io/scalecube/services/examples/gateway/WebsocketGatewayStub.java
  services-examples/src/main/java/io/scalecube/services/examples/helloworld/Example1.java
  services-examples/src/main/java/io/scalecube/services/examples/helloworld/Example2.java
  services-examples/src/main/java/io/scalecube/services/examples/orderbook/Example1.java
  services-gateway-http/src/main/java/io/scalecube/services/gateway/http/HttpGateway.java
  services-gateway-rsocket/src/main/java/io/scalecube/services/gateway/rsocket/RSocketGateway.java
  services-gateway-websocket/src/main/java/io/scalecube/services/gateway/ws/WebsocketGateway.java
  services/src/main/java/io/scalecube/services/Microservices.java
  services/src/main/java/io/scalecube/services/Reflect.java
  services/src/main/java/io/scalecube/services/ServiceCall.java
  services/src/main/java/io/scalecube/services/ServiceProvider.java
  services/src/main/java/io/scalecube/services/gateway/Gateway.java
  services/src/test/java/io/scalecube/services/ErrorFlowTest.java
  services/src/test/java/io/scalecube/services/ServiceCallLocalTest.java
  services/src/test/java/io/scalecube/services/ServiceCallRemoteTest.java
  services/src/test/java/io/scalecube/services/ServiceLocalTest.java
  services/src/test/java/io/scalecube/services/ServiceRemoteTest.java
  services/src/test/java/io/scalecube/services/ServiceTransportTest.java
  services/src/test/java/io/scalecube/services/StreamingServiceTest.java
  services/src/test/java/io/scalecube/services/routings/RoutersTest.java
  services/src/test/java/io/scalecube/services/routings/ServiceTagsExample.java
  services/src/test/java/io/scalecube/services/sut/CoarseGrainedServiceImpl.java
Labels: API change ⚠️, Improvement ↗️, 👁️ ready for review 👁️

#522 Refactor gateway bootstrap process
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/gateway/AbstractBenchmarkState.java
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/gateway/distributed/DistributedBenchmarkState.java
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/gateway/distributed/http/DistributedRequestOneBenchmark.java
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/gateway/distributed/rsocket/DistributedInfiniteStreamBenchmark.java
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/gateway/distributed/rsocket/DistributedRequestOneBenchmark.java
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/gateway/distributed/websocket/DistributedInfiniteStreamBenchmark.java
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/gateway/distributed/websocket/DistributedRequestOneBenchmark.java
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/gateway/remote/RemoteBenchmarkState.java
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/gateway/remote/http/RemoteRequestOneBenchmark.java
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/gateway/remote/rsocket/RemoteInfiniteStreamBenchmark.java
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/gateway/remote/rsocket/RemoteRequestOneBenchmark.java
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/gateway/remote/websocket/RemoteInfiniteStreamBenchmark.java
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/gateway/remote/websocket/RemoteRequestOneBenchmark.java
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/gateway/standalone/StandaloneBenchmarkState.java
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/gateway/standalone/http/StandaloneRequestOneBenchmark.java
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/gateway/standalone/rsocket/StandaloneInfiniteStreamBenchmark.java
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/gateway/standalone/rsocket/StandaloneRequestOneBenchmark.java
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/gateway/standalone/websocket/StandaloneInfiniteStreamBenchmark.java
  services-benchmarks/src/main/java/io/scalecube/services/benchmarks/gateway/standalone/websocket/StandaloneRequestOneBenchmark.java
  services-discovery/src/main/java/io/scalecube/services/discovery/ScalecubeServiceDiscovery.java
  services-examples/src/main/java/io/scalecube/services/examples/BootstrapExample.java
  services-examples/src/main/java/io/scalecube/services/examples/gateway/HttpGatewayExample.java
  services-examples/src/main/java/io/scalecube/services/examples/gateway/WebsocketGatewayExample.java
  services-examples/src/main/resources/META-INF/services/io.scalecube.services.gateway.Gateway
  services-gateway-clientsdk/src/main/java/io/scalecube/services/gateway/clientsdk/Client.java
  services-gateway-clientsdk/src/main/java/io/scalecube/services/gateway/clientsdk/ClientSettings.java
  services-gateway-common/src/main/java/io/scalecube/services/gateway/GatewayTemplate.java
  services-gateway-http/src/main/java/io/scalecube/services/gateway/http/HttpGateway.java
  services-gateway-http/src/main/resources/META-INF/services/io.scalecube.services.gateway.Gateway
  services-gateway-rsocket/src/main/java/io/scalecube/services/gateway/rsocket/RSocketGateway.java
  services-gateway-rsocket/src/main/resources/META-INF/services/io.scalecube.services.gateway.Gateway
  services-gateway-runner/src/main/java/io/scalecube/services/gateway/GatewayRunner.java
  services-gateway-tests/src/test/java/io/scalecube/services/gateway/AbstractGatewayExtension.java
  services-gateway-tests/src/test/java/io/scalecube/services/gateway/http/HttpGatewayExtension.java
  services-gateway-tests/src/test/java/io/scalecube/services/gateway/rsocket/RSocketClientSdkDisconnectTest.java
  services-gateway-tests/src/test/java/io/scalecube/services/gateway/rsocket/RsocketGatewayExtension.java
  services-gateway-tests/src/test/java/io/scalecube/services/gateway/websocket/WebsocketGatewayExtension.java
  services-gateway-websocket/src/main/java/io/scalecube/services/gateway/ws/WebsocketGateway.java
  services-gateway-websocket/src/main/resources/META-INF/services/io.scalecube.services.gateway.Gateway
  services-transport-rsocket/src/main/java/io/scalecube/services/transport/rsocket/RSocketServerTransport.java
  services/src/main/java/io/scalecube/services/Microservices.java
  services/src/main/java/io/scalecube/services/MicroservicesMBean.java
  services/src/main/java/io/scalecube/services/gateway/Gateway.java
  services/src/main/java/io/scalecube/services/gateway/GatewayConfig.java
  services/src/main/java/io/scalecube/services/gateway/GatewayMetrics.java
  services/src/main/java/io/scalecube/services/gateway/GatewayOptions.java
  services/src/test/java/io/scalecube/services/ErrorFlowTest.java
  services/src/test/java/io/scalecube/services/ServiceCallLocalTest.java
  services/src/test/java/io/scalecube/services/ServiceCallRemoteTest.java
  services/src/test/java/io/scalecube/services/ServiceLocalTest.java
  services/src/test/java/io/scalecube/services/ServiceRemoteTest.java
  services/src/test/java/io/scalecube/services/StreamingServiceTest.java
  services/src/test/java/io/scalecube/services/routings/RoutersTest.java
Labels: 👁️ ready for review 👁️

#528 Added scheduler to start microservices with it
  services/src/main/java/io/scalecube/services/Microservices.java
Labels: 👁️ ready for review 👁️

#531 Updated rsocket version
  pom.xml
  services-examples/src/main/java/io/scalecube/services/examples/BenchmarkServiceImpl.java
Labels: 👁️ ready for review 👁️

#534 Added more discovery events tests
  services-discovery/src/main/java/io/scalecube/services/discovery/ScalecubeServiceDiscovery.java
  services/src/test/java/io/scalecube/services/ServiceRegistryEventsTest.java
  services/src/test/java/io/scalecube/services/sut/AnnotationService.java
  services/src/test/java/io/scalecube/services/sut/AnnotationServiceImpl.java
Labels: Critical 🔥, 👁️ ready for review 👁️

#539 Fixed not expected behavior in service transport bootstrap
  services/src/main/java/io/scalecube/services/Microservices.java
Labels: Improvement ↗️, 👁️ ready for review 👁️
