Repository scalecube/scalecube-services, pull requests merged in 2019-04, with the labels that each got.

#544 Updated rsocket version (fixes connection closing)
  pom.xml
Labels: Critical 🔥, 🐞 Bug 🐞, 👁️ ready for review 👁️

#546 make transport optional
  services-api/src/main/java/io/scalecube/services/ServiceEndpoint.java
  services-api/src/main/java/io/scalecube/services/ServiceReference.java
  services-api/src/main/java/io/scalecube/services/transport/api/Address.java
  services-gateway-tests/src/test/java/io/scalecube/services/gateway/AbstractLocalGatewayExtension.java
  services-gateway-tests/src/test/java/io/scalecube/services/gateway/http/HttpLocalGatewayExtension.java
  services-gateway-tests/src/test/java/io/scalecube/services/gateway/http/HttpLocalGatewayTest.java
  services-gateway-tests/src/test/java/io/scalecube/services/gateway/rsocket/RSocketLocalGatewayTest.java
  services-gateway-tests/src/test/java/io/scalecube/services/gateway/rsocket/RsocketLocalGatewayExtension.java
  services-gateway-tests/src/test/java/io/scalecube/services/gateway/websocket/WebsocketLocalGatewayExtension.java
  services-gateway-tests/src/test/java/io/scalecube/services/gateway/websocket/WebsocketLocalGatewayTest.java
  services/src/main/java/io/scalecube/services/Microservices.java
  services/src/main/java/io/scalecube/services/ServiceCall.java
  services/src/main/java/io/scalecube/services/discovery/ServiceScanner.java
Labels: feature ⚙️, 👁️ ready for review 👁️

#548 remove transport and discovery from local tests.
  services-api/src/main/java/io/scalecube/services/api/ErrorData.java
  services-api/src/main/java/io/scalecube/services/api/Qualifier.java
  services/src/test/java/io/scalecube/services/ServiceLocalTest.java
  services/src/test/java/io/scalecube/services/routings/sut/RandomCollection.java
  services/src/test/java/io/scalecube/services/sut/GreetingService.java
Labels: 👁️ ready for review 👁️
